//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Granula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Granula()
        {
            this.KorisnikGranula = new HashSet<KorisnikGranula>();
            this.OdnosGranula = new HashSet<OdnosGranula>();
            this.OdnosGranula1 = new HashSet<OdnosGranula>();
            this.ZadatakGranula = new HashSet<ZadatakGranula>();
        }
    
        public int sifraGranule { get; set; }
        public string nazivGranule { get; set; }
        public int sifraKoncepta { get; set; }
        public int ukupnaSlozenost { get; set; }
    
        public virtual Koncept Koncept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KorisnikGranula> KorisnikGranula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdnosGranula> OdnosGranula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdnosGranula> OdnosGranula1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZadatakGranula> ZadatakGranula { get; set; }
    }
}
