//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikGranula
    {
        public int sifraKorisnikGranula { get; set; }
        public int sifraKorisnika { get; set; }
        public int sifraGranule { get; set; }
        public double znanje { get; set; }
    
        public virtual Granula Granula { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
