//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikKoncept
    {
        public int sifraKorisnikKoncept { get; set; }
        public int sifraKorisnika { get; set; }
        public int sifraKoncepta { get; set; }
        public double znanje { get; set; }
    
        public virtual Koncept Koncept { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
