//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Baza : DbContext
    {
        public Baza()
            : base("name=Baza")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AdminPredmet> AdminPredmet { get; set; }
        public virtual DbSet<Granula> Granula { get; set; }
        public virtual DbSet<Koncept> Koncept { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<KorisnikGranula> KorisnikGranula { get; set; }
        public virtual DbSet<KorisnikKoncept> KorisnikKoncept { get; set; }
        public virtual DbSet<KorisnikPredmet> KorisnikPredmet { get; set; }
        public virtual DbSet<OdnosGranula> OdnosGranula { get; set; }
        public virtual DbSet<OdnosKoncepata> OdnosKoncepata { get; set; }
        public virtual DbSet<OdnosZnanja> OdnosZnanja { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<Provjera> Provjera { get; set; }
        public virtual DbSet<ProvjeraZadatak> ProvjeraZadatak { get; set; }
        public virtual DbSet<Slozenost> Slozenost { get; set; }
        public virtual DbSet<VrstaProvjere> VrstaProvjere { get; set; }
        public virtual DbSet<VrstaZadatka> VrstaZadatka { get; set; }
        public virtual DbSet<Zadatak> Zadatak { get; set; }
        public virtual DbSet<ZadatakGranula> ZadatakGranula { get; set; }
        public virtual DbSet<ZadatakVrstaZadatka> ZadatakVrstaZadatka { get; set; }
    }
}
