//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdnosZnanja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OdnosZnanja()
        {
            this.OdnosGranula = new HashSet<OdnosGranula>();
            this.OdnosKoncepata = new HashSet<OdnosKoncepata>();
        }
    
        public int sifraOdnosa { get; set; }
        public string nazivOdnosa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdnosGranula> OdnosGranula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdnosKoncepata> OdnosKoncepata { get; set; }
    }
}
