//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdnosGranula
    {
        public int sifraOdnosaGranula { get; set; }
        public int sifraNizeGranule { get; set; }
        public int sifraViseGranule { get; set; }
        public int sifraOdnosa { get; set; }
    
        public virtual Granula Granula { get; set; }
        public virtual Granula Granula1 { get; set; }
        public virtual OdnosZnanja OdnosZnanja { get; set; }
    }
}
