//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdnosKoncepata
    {
        public int sifraOdnosaKoncepata { get; set; }
        public int sifraNizegKon { get; set; }
        public int sifraVisegKon { get; set; }
        public int sifraOdnosa { get; set; }
    
        public virtual Koncept Koncept { get; set; }
        public virtual Koncept Koncept1 { get; set; }
        public virtual OdnosZnanja OdnosZnanja { get; set; }
    }
}
