//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provjera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provjera()
        {
            this.ProvjeraZadatak = new HashSet<ProvjeraZadatak>();
        }
    
        public int sifraProvjere { get; set; }
        public int sifraVrsteProvjere { get; set; }
        public int sifraKorisnika { get; set; }
        public int sifraPredmeta { get; set; }
        public int SkaliraniUkupniBrojBodova { get; set; }
        public Nullable<double> ostvareniBrojBodova { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual VrstaProvjere VrstaProvjere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvjeraZadatak> ProvjeraZadatak { get; set; }
    }
}
