//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZadatakGranula
    {
        public int sifraZadatakGranula { get; set; }
        public int sifraZadatka { get; set; }
        public int sifraGranule { get; set; }
        public int sadrzaj { get; set; }
    
        public virtual Granula Granula { get; set; }
        public virtual Zadatak Zadatak { get; set; }
    }
}
