//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.BP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadatak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadatak()
        {
            this.ProvjeraZadatak = new HashSet<ProvjeraZadatak>();
            this.ZadatakGranula = new HashSet<ZadatakGranula>();
            this.ZadatakVrstaZadatka = new HashSet<ZadatakVrstaZadatka>();
        }
    
        public int sifraZadatka { get; set; }
        public string pitanje { get; set; }
        public string izraz { get; set; }
        public byte[] slika { get; set; }
        public string parametri { get; set; }
        public int sifraSlozenosti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvjeraZadatak> ProvjeraZadatak { get; set; }
        public virtual Slozenost Slozenost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZadatakGranula> ZadatakGranula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZadatakVrstaZadatka> ZadatakVrstaZadatka { get; set; }
    }
}
